apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: helloworld-datasource
  name: helloworld-datasource
spec:
  output:
    to:
      kind: ImageStreamTag
      name: helloworld-datasource:latest
  source:
    dockerfile: |-
      FROM jboss-eap74-openjdk17-runtime-openshift:7.4
      COPY /server $JBOSS_HOME
      USER root
      RUN chown -R jboss:root $JBOSS_HOME && chmod -R ug+rwX $JBOSS_HOME
      USER jboss
      CMD $JBOSS_HOME/bin/openshift-launch.sh
    images:
    - from:
        kind: ImageStreamTag
        name: helloworld-datasource-build-artifacts:latest
      paths:
      - destinationDir: .
        sourcePath: /s2i-output/server/
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-eap74-openjdk17-runtime-openshift:7.4
        namespace: eap7-demo 
      imageOptimizationPolicy: SkipLayers
    type: Docker
  triggers:
  - imageChange:
      from:
        kind: ImageStreamTag
        name: helloworld-datasource-build-artifacts:latest
    type: ImageChange
  - type: ConfigChange
